{% set version = "1.16.4" %}

package:
  name: pygltflib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygltflib/pygltflib-{{ version }}.tar.gz
  sha256: 7816253ef51b07a208864b94332bce8c509aa0f9b827d8771cf271293ecebb11

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - dataclasses-json >=0.0.25
    - deprecated

test:
  imports:
    - pygltflib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/dodgyville/pygltflib
  summary: Python library for reading, writing and managing 3D objects in the Khronos Group gltf and gltf2 formats.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
